"""changed the primary key in admin table

Revision ID: 05ffc3e41f7d
Revises: dd6ce2bd4e4a
Create Date: 2024-08-07 16:58:50.554627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ffc3e41f7d'
down_revision = 'dd6ce2bd4e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.drop_index('admin_id')
        batch_op.create_unique_constraint(None, ['companyname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adminuser', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('admin_id', ['admin_id'], unique=True)

    # ### end Alembic commands ###
