"""Changed the user increment

Revision ID: 34eac372e7dd
Revises: 3c2a2b31a7b8
Create Date: 2024-06-21 16:24:34.926523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34eac372e7dd'
down_revision = '3c2a2b31a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('id',
            existing_type=sa.Integer(),
            type_=sa.Integer(),
            server_default=None 
        )
        batch_op.execute("ALTER TABLE user AUTO_INCREMENT = 100001")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
