"""A few changes

Revision ID: 7d941efaacdf
Revises: 3d39558d3db4
Create Date: 2024-06-15 13:11:26.767639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d941efaacdf'
down_revision = '3d39558d3db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('id')
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_constraint('credentials_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('recyclingtracker', schema=None) as batch_op:
        batch_op.drop_constraint('recyclingtracker_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('waste_collection_schedule', schema=None) as batch_op:
        batch_op.drop_constraint('waste_collection_schedule_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('wastecollection', schema=None) as batch_op:
        batch_op.drop_constraint('wastecollection_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wastecollection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wastecollection_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('waste_collection_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('waste_collection_schedule_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('recyclingtracker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recyclingtracker_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credentials_ibfk_1', 'users', ['id'], ['id'])

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
