"""some changes

Revision ID: 8de3fe7d288b
Revises: 
Create Date: 2024-06-22 09:32:20.867658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8de3fe7d288b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['username'], ['username'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('recyclingeffort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('recyclingeffort_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['username'], ['username'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_name')

    with op.batch_alter_table('waste_collection_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('waste_collection_schedule_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['username'], ['username'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('wastecollection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('wastecollection_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['username'], ['username'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wastecollection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wastecollection_ibfk_1', 'user', ['user_name'], ['username'])
        batch_op.drop_column('username')

    with op.batch_alter_table('waste_collection_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('waste_collection_schedule_ibfk_1', 'user', ['user_name'], ['username'])
        batch_op.drop_column('username')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.create_foreign_key('user_ibfk_1', 'user', ['user_name'], ['username'])

    with op.batch_alter_table('recyclingeffort', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recyclingeffort_ibfk_1', 'user', ['user_name'], ['username'])
        batch_op.drop_column('username')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_ibfk_1', 'user', ['user_name'], ['username'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
