"""pleaseee

Revision ID: fa4c75853274
Revises: 34eac372e7dd
Create Date: 2024-06-21 16:32:02.184065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa4c75853274'
down_revision = '34eac372e7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recyclingeffort', schema=None) as batch_op:
        batch_op.alter_column('waste_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=55),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recyclingeffort', schema=None) as batch_op:
        batch_op.alter_column('waste_name',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
