name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-latest
          - macos-10.15
          - windows-latest
          - windows-2019
        python-version:
          - '3.12.3'
          - '3.11'
          - '3.10'
          - '3.9'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up virtual environment and install dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          python -m venv venv
          source venv/bin/activate
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          python3 -m venv venv
          source venv/bin/activate
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          python -m venv venv
          .\venv\Scripts\activate.bat
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi

        # Install dependencies
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
