name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04, macos-latest, macos-10.15, windows-latest, windows-2019]
        python-version: ['3.12.3', '3.11', '3.10', '3.9']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Debug Python Version
      run: python --version

    - name: Install system dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y libmysqlclient-dev
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install mysql-client
          echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> ~/.zshrc
          source ~/.zshrc
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install mysql
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
      shell: bash

    - name: Debug System Dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          dpkg -l | grep libmysqlclient-dev
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          mysql --version
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          mysql --version
      shell: bash

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up virtual environment and install dependencies
      run: |
        python -m venv venv
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          venv\Scripts\activate
        else
          source venv/bin/activate
        fi
        pip install -r requirements.txt
      shell: bash

    - name: Debug Virtual Environment
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          venv\Scripts\python --version
        else
          source venv/bin/activate
          python --version
      shell: bash

    - name: Run tests
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          venv\Scripts\pytest
        else
          source venv/bin/activate
          pytest
      shell: bash
